// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/protavo/drivertest/content.proto

package drivertest

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TestContent struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestContent) Reset()         { *m = TestContent{} }
func (m *TestContent) String() string { return proto.CompactTextString(m) }
func (*TestContent) ProtoMessage()    {}
func (*TestContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_62bd760cf64760b5, []int{0}
}
func (m *TestContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestContent.Unmarshal(m, b)
}
func (m *TestContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestContent.Marshal(b, m, deterministic)
}
func (dst *TestContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestContent.Merge(dst, src)
}
func (m *TestContent) XXX_Size() int {
	return xxx_messageInfo_TestContent.Size(m)
}
func (m *TestContent) XXX_DiscardUnknown() {
	xxx_messageInfo_TestContent.DiscardUnknown(m)
}

var xxx_messageInfo_TestContent proto.InternalMessageInfo

func (m *TestContent) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*TestContent)(nil), "protavo.drivertest.TestContent")
}

func init() {
	proto.RegisterFile("src/protavo/drivertest/content.proto", fileDescriptor_content_62bd760cf64760b5)
}

var fileDescriptor_content_62bd760cf64760b5 = []byte{
	// 106 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x29, 0x2e, 0x4a, 0xd6,
	0x2f, 0x28, 0xca, 0x2f, 0x49, 0x2c, 0xcb, 0xd7, 0x4f, 0x29, 0xca, 0x2c, 0x4b, 0x2d, 0x2a, 0x49,
	0x2d, 0x2e, 0xd1, 0x4f, 0xce, 0xcf, 0x2b, 0x49, 0xcd, 0x2b, 0xd1, 0x03, 0x49, 0xe5, 0x0b, 0x09,
	0x41, 0x55, 0xe8, 0x21, 0x54, 0x28, 0x29, 0x72, 0x71, 0x87, 0xa4, 0x16, 0x97, 0x38, 0x43, 0x14,
	0x0a, 0x09, 0x71, 0xb1, 0xa4, 0x24, 0x96, 0x24, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81,
	0xd9, 0x4e, 0x3c, 0x51, 0x5c, 0x08, 0x0d, 0x49, 0x6c, 0x60, 0xb3, 0x8c, 0x01, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x54, 0x29, 0xe8, 0x8a, 0x73, 0x00, 0x00, 0x00,
}
