// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/protavobolt/internal/database/data.proto

package database

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Record is the definitive record of a document's existence.
type Record struct {
	// revision is a 1-based document version number used to implement
	// optimistic concurrency control.
	Revision uint64 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	// keys is the set of indexing keys applied to the document. keys are used
	// to quickly find a document or set of documents based on identifieres
	// other than the document ID.
	Keys map[string]uint32 `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	// created_at is the time at which the document was created. The value is
	// set automatically when the document is saved.
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// updated_at is the time at which the document was last modified. The value
	// is set automatically when the document is saved.
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_a587a6b6b981b685, []int{0}
}
func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (dst *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(dst, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetRevision() uint64 {
	if m != nil {
		return m.Revision
	}
	return 0
}

func (m *Record) GetKeys() map[string]uint32 {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *Record) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Record) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

// Content is container for a document's content.
type Content struct {
	// headers is an arbitrary set of key/value pairs that is persisted along
	// with the document content.
	Headers map[string]string `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// content is the application-defined document content.
	Content              *any.Any `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Content) Reset()         { *m = Content{} }
func (m *Content) String() string { return proto.CompactTextString(m) }
func (*Content) ProtoMessage()    {}
func (*Content) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_a587a6b6b981b685, []int{1}
}
func (m *Content) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Content.Unmarshal(m, b)
}
func (m *Content) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Content.Marshal(b, m, deterministic)
}
func (dst *Content) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Content.Merge(dst, src)
}
func (m *Content) XXX_Size() int {
	return xxx_messageInfo_Content.Size(m)
}
func (m *Content) XXX_DiscardUnknown() {
	xxx_messageInfo_Content.DiscardUnknown(m)
}

var xxx_messageInfo_Content proto.InternalMessageInfo

func (m *Content) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *Content) GetContent() *any.Any {
	if m != nil {
		return m.Content
	}
	return nil
}

// Key is an instance of a named key.
type Key struct {
	Type                 uint32          `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Documents            map[string]bool `protobuf:"bytes,2,rep,name=documents,proto3" json:"documents,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Key) Reset()         { *m = Key{} }
func (m *Key) String() string { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()    {}
func (*Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_a587a6b6b981b685, []int{2}
}
func (m *Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key.Unmarshal(m, b)
}
func (m *Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key.Marshal(b, m, deterministic)
}
func (dst *Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key.Merge(dst, src)
}
func (m *Key) XXX_Size() int {
	return xxx_messageInfo_Key.Size(m)
}
func (m *Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Key proto.InternalMessageInfo

func (m *Key) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Key) GetDocuments() map[string]bool {
	if m != nil {
		return m.Documents
	}
	return nil
}

func init() {
	proto.RegisterType((*Record)(nil), "protavo.bolt.Record")
	proto.RegisterMapType((map[string]uint32)(nil), "protavo.bolt.Record.KeysEntry")
	proto.RegisterType((*Content)(nil), "protavo.bolt.Content")
	proto.RegisterMapType((map[string]string)(nil), "protavo.bolt.Content.HeadersEntry")
	proto.RegisterType((*Key)(nil), "protavo.bolt.Key")
	proto.RegisterMapType((map[string]bool)(nil), "protavo.bolt.Key.DocumentsEntry")
}

func init() {
	proto.RegisterFile("src/protavobolt/internal/database/data.proto", fileDescriptor_data_a587a6b6b981b685)
}

var fileDescriptor_data_a587a6b6b981b685 = []byte{
	// 386 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcf, 0x8e, 0xd3, 0x30,
	0x10, 0xc6, 0xe5, 0xb6, 0x6c, 0x9b, 0xd9, 0x5d, 0x84, 0xac, 0x3d, 0x84, 0x1c, 0x20, 0xea, 0x29,
	0x07, 0xe4, 0x48, 0xe5, 0x00, 0xac, 0x56, 0x48, 0xe5, 0x8f, 0x84, 0xd4, 0x9b, 0xc5, 0x89, 0x0b,
	0x72, 0x92, 0x61, 0x89, 0x36, 0xb5, 0x23, 0xc7, 0xa9, 0xe4, 0x27, 0xe0, 0x11, 0x78, 0x10, 0x5e,
	0x10, 0xc5, 0x8e, 0x4b, 0xca, 0x1e, 0x7a, 0x9b, 0xd1, 0xfc, 0xbe, 0xe4, 0xf7, 0x29, 0x81, 0x57,
	0x9d, 0x2e, 0xf3, 0x56, 0x2b, 0x23, 0x0e, 0xaa, 0x50, 0x8d, 0xc9, 0x6b, 0x69, 0x50, 0x4b, 0xd1,
	0xe4, 0x95, 0x30, 0xa2, 0x10, 0x1d, 0xba, 0x81, 0x0d, 0x88, 0xa2, 0x57, 0x23, 0xc9, 0x06, 0x34,
	0x79, 0x7e, 0xaf, 0xd4, 0x7d, 0x83, 0x2e, 0xae, 0x8a, 0xfe, 0x47, 0x2e, 0xa4, 0xf5, 0x60, 0xf2,
	0xf2, 0xff, 0x93, 0xa9, 0xf7, 0xd8, 0x19, 0xb1, 0x6f, 0x3d, 0xb0, 0xfe, 0x35, 0x83, 0x0b, 0x8e,
	0xa5, 0xd2, 0x15, 0x4d, 0x60, 0xa5, 0xf1, 0x50, 0x77, 0xb5, 0x92, 0x31, 0x49, 0x49, 0xb6, 0xe0,
	0xc7, 0x9d, 0x6e, 0x60, 0xf1, 0x80, 0xb6, 0x8b, 0x67, 0xe9, 0x3c, 0xbb, 0xdc, 0xbc, 0x60, 0xd3,
	0xf7, 0x33, 0x9f, 0x67, 0x3b, 0xb4, 0xdd, 0x67, 0x69, 0xb4, 0xe5, 0x8e, 0xa5, 0xef, 0x00, 0x4a,
	0x8d, 0xc2, 0x60, 0xf5, 0x5d, 0x98, 0x78, 0x9e, 0x92, 0xec, 0x72, 0x93, 0x30, 0x2f, 0xc4, 0x82,
	0x10, 0xfb, 0x1a, 0x84, 0x78, 0x34, 0xd2, 0x5b, 0x33, 0x44, 0xfb, 0xb6, 0x0a, 0xd1, 0xc5, 0xf9,
	0xe8, 0x48, 0x6f, 0x4d, 0xf2, 0x06, 0xa2, 0xa3, 0x08, 0x7d, 0x06, 0xf3, 0x07, 0xb4, 0xae, 0x4d,
	0xc4, 0x87, 0x91, 0xde, 0xc0, 0x93, 0x83, 0x68, 0x7a, 0x8c, 0x67, 0x29, 0xc9, 0xae, 0xb9, 0x5f,
	0x6e, 0x67, 0x6f, 0xc9, 0xfa, 0x0f, 0x81, 0xe5, 0x47, 0x25, 0x0d, 0x4a, 0x43, 0xef, 0x60, 0xf9,
	0x13, 0x45, 0x85, 0xba, 0x8b, 0x89, 0x6b, 0xbc, 0x3e, 0x6d, 0x3c, 0x72, 0xec, 0x8b, 0x87, 0x7c,
	0xeb, 0x10, 0xa1, 0x0c, 0x96, 0xa5, 0x07, 0x46, 0xf5, 0x9b, 0x47, 0xea, 0x5b, 0x69, 0x79, 0x80,
	0x92, 0x5b, 0xb8, 0x9a, 0x3e, 0xe8, 0x9c, 0x75, 0x34, 0xb5, 0xfe, 0x4d, 0x60, 0xbe, 0x43, 0x4b,
	0x29, 0x2c, 0x8c, 0x6d, 0xd1, 0x85, 0xae, 0xb9, 0x9b, 0xe9, 0x7b, 0x88, 0x2a, 0x55, 0xf6, 0x7b,
	0x94, 0x26, 0x7c, 0xb9, 0xf4, 0xb4, 0xc7, 0x0e, 0x2d, 0xfb, 0x14, 0x10, 0xdf, 0xe2, 0x5f, 0x24,
	0xb9, 0x83, 0xa7, 0xa7, 0xc7, 0x73, 0x66, 0xab, 0x89, 0xd9, 0x07, 0xf8, 0xb6, 0x0a, 0xbf, 0x6e,
	0x71, 0xe1, 0x8a, 0xbf, 0xfe, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x03, 0xc7, 0xdc, 0xd9, 0xe6, 0x02,
	0x00, 0x00,
}
