// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/protavo/document/content.proto

package document

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StringContentType struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringContentType) Reset()         { *m = StringContentType{} }
func (m *StringContentType) String() string { return proto.CompactTextString(m) }
func (*StringContentType) ProtoMessage()    {}
func (*StringContentType) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_e73a0e87095654e0, []int{0}
}
func (m *StringContentType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringContentType.Unmarshal(m, b)
}
func (m *StringContentType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringContentType.Marshal(b, m, deterministic)
}
func (dst *StringContentType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringContentType.Merge(dst, src)
}
func (m *StringContentType) XXX_Size() int {
	return xxx_messageInfo_StringContentType.Size(m)
}
func (m *StringContentType) XXX_DiscardUnknown() {
	xxx_messageInfo_StringContentType.DiscardUnknown(m)
}

var xxx_messageInfo_StringContentType proto.InternalMessageInfo

func (m *StringContentType) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*StringContentType)(nil), "protavo.document.StringContentType")
}

func init() {
	proto.RegisterFile("src/protavo/document/content.proto", fileDescriptor_content_e73a0e87095654e0)
}

var fileDescriptor_content_e73a0e87095654e0 = []byte{
	// 111 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2a, 0x2e, 0x4a, 0xd6,
	0x2f, 0x28, 0xca, 0x2f, 0x49, 0x2c, 0xcb, 0xd7, 0x4f, 0xc9, 0x4f, 0x2e, 0xcd, 0x4d, 0xcd, 0x2b,
	0xd1, 0x4f, 0xce, 0xcf, 0x2b, 0x49, 0xcd, 0x2b, 0xd1, 0x03, 0x49, 0xe4, 0x0b, 0x09, 0x40, 0xe5,
	0xf5, 0x60, 0xf2, 0x4a, 0x9a, 0x5c, 0x82, 0xc1, 0x25, 0x45, 0x99, 0x79, 0xe9, 0xce, 0x10, 0x85,
	0x21, 0x95, 0x05, 0xa9, 0x42, 0x22, 0x5c, 0xac, 0x65, 0x89, 0x39, 0xa5, 0xa9, 0x12, 0x8c, 0x0a,
	0x8c, 0x1a, 0x9c, 0x41, 0x10, 0x8e, 0x13, 0x57, 0x14, 0x07, 0x4c, 0x5b, 0x12, 0x1b, 0xd8, 0x3c,
	0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x4d, 0x6a, 0x13, 0x75, 0x00, 0x00, 0x00,
}
